// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ijvn6lqUZ2GX9gAtDttzY7SDAcnpsUU',
    appId: '1:1075627468657:web:063d7193a246e37617b8d0',
    messagingSenderId: '1075627468657',
    projectId: 'student-detail-4f07c',
    authDomain: 'student-detail-4f07c.firebaseapp.com',
    databaseURL: 'https://student-detail-4f07c-default-rtdb.firebaseio.com',
    storageBucket: 'student-detail-4f07c.appspot.com',
    measurementId: 'G-PC73NBWYEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv8mPz7_FE477KUIWUqYLr2x7KuwV4MIg',
    appId: '1:1075627468657:android:d33362daa29be49e17b8d0',
    messagingSenderId: '1075627468657',
    projectId: 'student-detail-4f07c',
    databaseURL: 'https://student-detail-4f07c-default-rtdb.firebaseio.com',
    storageBucket: 'student-detail-4f07c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZDh830TaKgMLlmUVj8m6fkxsSO-JZzYM',
    appId: '1:1075627468657:ios:712f93e99fb9802117b8d0',
    messagingSenderId: '1075627468657',
    projectId: 'student-detail-4f07c',
    databaseURL: 'https://student-detail-4f07c-default-rtdb.firebaseio.com',
    storageBucket: 'student-detail-4f07c.appspot.com',
    iosBundleId: 'com.example.signx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZDh830TaKgMLlmUVj8m6fkxsSO-JZzYM',
    appId: '1:1075627468657:ios:712f93e99fb9802117b8d0',
    messagingSenderId: '1075627468657',
    projectId: 'student-detail-4f07c',
    databaseURL: 'https://student-detail-4f07c-default-rtdb.firebaseio.com',
    storageBucket: 'student-detail-4f07c.appspot.com',
    iosBundleId: 'com.example.signx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ijvn6lqUZ2GX9gAtDttzY7SDAcnpsUU',
    appId: '1:1075627468657:web:f0f15dee9d5996c317b8d0',
    messagingSenderId: '1075627468657',
    projectId: 'student-detail-4f07c',
    authDomain: 'student-detail-4f07c.firebaseapp.com',
    databaseURL: 'https://student-detail-4f07c-default-rtdb.firebaseio.com',
    storageBucket: 'student-detail-4f07c.appspot.com',
    measurementId: 'G-TT191WXN6P',
  );

}